### PR TITLE
discount items initial setting

### PR DESCRIPTION
**Pull request by Yannickdjoa**
discount items initial setting

### CODE REVIEW

**Review by uniresa-admin — COMMENTED** [review]
finalise the discount card before  merging

**Comment by Yannickdjoa** [comment]
ok I will work on it tomorrow and submit

**Review by uniresa-admin — CHANGES_REQUESTED** [review]
ok sending back the PR for changes

**Comment by Yannickdjoa** [comment]
updates done

**Review by uniresa-admin — APPROVED** [review]
Approved

**Pull request merged**
